site_name: prime_estate
site_description: A real estaste django rest framework project
repo_url: https://github.com/TobiFon/Primeestate
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/TobiFon">TobiFon</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
